import { NextIntlClientProvider, useMessages } from 'next-intl'
import localFont from 'next/font/local'
import { Sidebar } from '@/components/Sidebar'
import LocalSwitcher from '@/components/LocalSwitcher'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

const iranYekan = localFont({
  src: './fonts/iranyekanwebregular.woff',
  variable: '--font-iran-yekan',
  weight: '400',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {
  const {
    children,
    params: {
      locale
    }
  } = props
  const messages = useMessages()
  const fontVariables = (locale === 'fa') ? iranYekan.variable : `${geistMono.variable} ${geistSans.variable}`

  return (
    <html
      lang={locale}
      dir={(locale === 'fa') ? 'rtl' : 'ltr'}
    >
      <body className={`${fontVariables} antialiased flex`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div className={'rounded-md flex flex-col md:flex-row bg-gray-100 dark:bg-neutral-800 w-full flex-1 mx-auto border border-neutral-200 dark:border-neutral-700 overflow-hidden h-screen'}>
            <Sidebar />
            <div className='flex-1 bg-[#171717]'>
              <LocalSwitcher />
              <div className='ms-4 mt-8'>
                {children}
              </div>
            </div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
